version: '3'
services:
  web:
    environment:
      - DB_URI=mongo
      - DB_PORT=27017
    build: .
    command: npm run watch
    volumes:
      - .:/usr/app/
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /usr/app/node_modules
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo

