version: '3'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: builder
    command: npx wsrun -c build:watch
    volumes:
      - .:$REPO_MOUNT_POINT
  server:
    environment:
      - DB_URI=mongo
      - DB_PORT=27017
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_REFRESH_TOKEN
      - TWITCH_CLIENT_ID
      - TWITCH_TOKEN
      - TWITCH_USERNAME
    image: builder
    depends_on:
      - builder
    command: yarn workspace @treats-app/server run dev
    ports:
      - "3218:3218"
    volumes:
      - .:$REPO_MOUNT_POINT
      - ./packages/server/dev/.treats:/root/.treats
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - $REPO_MOUNT_POINT/node_modules
  web:
    depends_on:
      - builder
    image: builder
    environment:
      - SERVER_PROXY=http://server:3218
    command: yarn workspace @treats-app/web run dev
    ports:
      - "1234:1234"
    volumes:
      - .:$REPO_MOUNT_POINT
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - $REPO_MOUNT_POINT/node_modules
  mongo:
    container_name: mongo
    image: mongo

