version: '3'
services:
  server_builder:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: server_builder
    command: yarn build:watch
    volumes:
      - .:$REPO_MOUNT_POINT
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - $REPO_MOUNT_POINT/node_modules
  server:
    environment:
      - DB_URI=mongo
      - DB_PORT=27017
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_REFRESH_TOKEN
      - TWITCH_CLIENT_ID
      - TWITCH_TOKEN
      - TWITCH_USERNAME
    image: server_builder
    depends_on:
      - server_builder
    command: yarn dev:server
    ports:
      - "3218:3218"
    volumes:
      - .:$REPO_MOUNT_POINT
      - ./dev/.treats:/root/.treats
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - $REPO_MOUNT_POINT/node_modules
  mongo:
    container_name: mongo
    image: mongo

