version: '3'
services:
  app_builder:
    build: .
    image: app_builder
    command: yarn build:watch
    volumes:
      - .:/usr/app
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /usr/app/node_modules
  app:
    environment:
      - DB_URI=mongo
      - DB_PORT=27017
      - REDDIT_CLIENT_ID
      - REDDIT_CLIENT_SECRET
      - REDDIT_REFRESH_TOKEN
    image: app_builder
    depends_on:
      - app_builder
    command: yarn dev:server
    ports:
      - "3218:3218"
    volumes:
      - ./dist:/usr/app/dist
      - ./dev/.treats:/root/.treats
      # Tells container to ignore the mounted node_modules on the host,
      # use the one installed in the container
      # https://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /usr/app/node_modules
  mongo:
    container_name: mongo
    image: mongo

